substitutions:
  _SERVICE_NAME: "mvcapp-service"  # Ensure this matches your Cloud Run service name
  _REGION: "us-central1"
  _PROJECT_ID: "azuredemoapp-452210"
  _REPO_NAME: "mvcapp"

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated \
          --quiet  # Suppresses confirmation prompts for automation
