substitutions:
  _SERVICE_NAME: "mvcapp-service"
  _REGION: "us-central1"
  _PROJECT_ID: "azuredemoapp-452210"
  _REPO_NAME: "mvcapp"

options:
  logging: CLOUD_LOGGING_ONLY  # Ensure logs go to Cloud Logging only

steps:
  # Step 1: Authenticate with Service Account
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud auth activate-service-account --key-file=key.json
        gcloud auth configure-docker $_REGION-docker.pkg.dev

  # Step 2: Build the Docker image with a unique tag
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA",
      "-t", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID",
      "."
    ]

  # Step 3: Push the uniquely tagged image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID"]

images:
  - "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
  - "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID"
