name: Deploy to Google Cloud Run

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-mvc-app \
            --image=us-central1-docker.pkg.dev/azuredemoapp-452210/mvcapp/my-mvc-app:$GITHUB_SHA \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
